### ISSUE TITLE
Bad Graphics

### ISSUE THREAD

**Issue by FireHunterX** [Ivorforce/Psychedelicraft#17]
Mushrooms make everything brighter and brighter until everything is black and white, and peyote doesn't do anything.

Running on OS X Yosemite with the latest version of Java as of September 9 2015. I'll post a screenshot of my About This Mac page.

![2015-09-09_15 22 50](https://cloud.githubusercontent.com/assets/14205258/9772028/c75a23e8-5707-11e5-9240-c3cb005c1592.png)
![2015-09-09_15 22 53](https://cloud.githubusercontent.com/assets/14205258/9772031/c7633280-5707-11e5-9bb3-ce58361ad87c.png)
![2015-09-09_15 23 47](https://cloud.githubusercontent.com/assets/14205258/9772029/c7622156-5707-11e5-86ce-49a7b71b5607.png)
![2015-09-09_15 23 50_2](https://cloud.githubusercontent.com/assets/14205258/9772030/c7627f3e-5707-11e5-8f48-8b661b0dc2cc.png)
![2015-09-09_15 23 50](https://cloud.githubusercontent.com/assets/14205258/9772032/c7648cb6-5707-11e5-828c-3c58bed06e67.png)
![2015-09-09_15 22 53](https://cloud.githubusercontent.com/assets/14205258/9772061/f054762c-5707-11e5-8da0-81342983c3f3.png)
<img width="307" alt="screen shot 2015-09-09 at 3 30 00 pm" src="https://cloud.githubusercontent.com/assets/14205258/9772066/fa66b60c-5707-11e5-8d61-6457f92fc290.png">

**Comment by Ivorforce** [comment]
Hey,

you're doing two things here - firstly, you're taking too many drugs, to a point of overdosing, and secondly you aren't realizing drug effects are randomized. Try again and your results will differ.

~Ivorius

**Comment by FireHunterX** [comment]
Oh, so it's intended to do that? Even with 1? I just figured it was the graphics card not being supported.

**Comment by Ivorforce** [comment]
It's intended to do something - as I said, ranomized. The fact that it was so strong was probably because you took two drugs right after another, thinking one was ineffective.

**Comment by DPxKnightxZero** [comment]
I made that mistake before XD

**Comment by GunArm** [comment]
There is also an interaction issue with the Inventory Tweaks thing that automatically refills your hot bar with the same item (I think), but it makes it so that if you try to eat just one, it will eat two.
Example: If you are being really careful and hold down right mouse just long enough to hear the "chomp chomp chomp" sound of eating just once, and the number just goes down by one, but then a few seconds later the number will drop down one more, as it has somehow eaten two.  And then you trip harder than you expected.

I kinda think it would be good if the intensity of the drugs (especially mushrooms) was reduced by half or more.  I interpret the closed eye visuals (I assume that's what you were going for, where everything is washed out solid colors) are sortof a punishment for taking too much (because you are blind and your screen is just white with nothing cool to look at).  But they always take over after eating just two of something.  It would be nice if it took like 10 to get to that point.  And people had to work harder to dry more drugs to get the effects that a single one gives you.  Because the melty-drifty effects of a single one are awesome.

**Comment by Ivorforce** [comment]
10 is far too much - I intended one item of mushrooms to be equal to one 'normal' dose. 

I think currently you arrive at 1 if you eat about 3 of them, which I think makes sense for most cases.
